### PR TITLE
chore: Lossless PNG Compression

### PR DESCRIPTION
**Pull request by mikeirvingweb**
Perform a comparison of _PNGOUT_, _OptiPNG_, and _DeflOpt_ to create the smallest possible images, **100% lossless**

Do this before upload of more images - you can use [PNGGauntlet](https://pnggauntlet.com/) (Windows) or other software.

In this commit I have done just this, saving 1426.84 KB, as shown  

image

### CODE REVIEW

**Comment by minhh2792** [comment]
This is based on https://github.com/kornelski/pngquant, the better implementation for this is to use GitHub Actions

**Comment by mikeirvingweb** [comment]
yes, ideally you could have a GitHub Action to sort this on commit, but that is for you / someone else to sort out in GitHub Actions.

**Comment by Aikoyori** [comment]
i genuinely think providing the raw export from Affinity Designer and let the users know that they can compress it further should be enough

also ideally there would be GitHub actions set up for these

I'd also like to keep a bit of history on the repo so yeah

**Comment by mikeirvingweb** [comment]
Okay. That sounds sensible.

**Pull request closed without merging**
